### PR TITLE
Gmf27

### LINKED ISSUE #2: not working in some cases with a custom /etc/docker/daemon.json
### Current Behavior
Users cannot start the demo using `./install.sh` and installing everything locally (including database).

### Expected Behavior

App should start on port 8484 without errors. It should use the local database (i.e. docker container provided with install.sh script)

### Steps to Reproduce

1. Install a fresh Ubuntu flavor distribution (i.e. Pop!_OS 22.04 LTS x86_64 installation)
2. Install all prerequisites
3. By default, /etc/docker/daemon.json does not exist.
4. Add a basic /etc/docker/daemon.json (i.e. to override storage default config)
     ```
    {
        "data-root": "/storage/docker"
    }
    ```
5. Run `./install.sh` and kind of say yes to everything, also to install a local database.
6. Everything should be fine, but the app won't work correctly.
7. In docker logs file, you should see some connection error to `pg-gs.camptocamp.com`
    
### Additional Information

I do not override default network, however the presence of /etc/docker/daemon.json trigger the if case:
```
dbhost=172.17.0.1
# Check if the default network was overriden on this server
if [ -f /etc/docker/daemon.json ]
then
    dbhost=`sed -r 's/.*"bip" *\: *"([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+).*/\1/' /etc/docker/daemon.json`
fi
```
A simple fix could be an additional condition with a regex searching the presence of the string. What do you think ?

### PR DESCRIPTION
**Pull request by maltaesousa**
This PR:
 - Makes it work with 2.7
 - Uses integrated db instead of external
 - Closes #2

### CODE REVIEW

**Comment by remyguillaume** [comment]
Hello @maltaesousa,

For the moment, i doesn't work on my linux.
I get the following error/warning messages: 
```
Configuring GeoMapFish project...
OK.
Committing first version...
astuce: Utilisation de 'master' comme nom de la branche initiale. Le nom de la branche
astuce: par défaut peut changer. Pour configurer le nom de la branche initiale
astuce: pour tous les nouveaux dépôts, et supprimer cet avertissement, lancez :
astuce: 
astuce: 	git config --global init.defaultBranch <nom>
astuce: 
astuce: Les noms les plus utilisés à la place de 'master' sont 'main', 'trunk' et
astuce: 'development'. La branche nouvellement créée peut être rénommée avec :
astuce: 
astuce: 	git branch -m <nom>
OK.
Compiling GeoMapFish project...
Traceback (most recent call last):
  File "/tmp/gmf/my-super-gmf-app/./build", line 15, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
OK.
Configuring GeoMapFish Database...
WARN[0000] The "DOCKER_BASE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DOCKER_TAG" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GIT_HASH" variable is not set. Defaulting to a blank string. 
WARN[0000] The "PGSCHEMA" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GEOMAPFISH_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GEOMAPFISH_MAIN_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GEOMAPFISH_MAIN_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "POSTGRES_TAG" variable is not set. Defaulting to a blank string. 
WARN[0000] The "PGPASSWORD" variable is not set. Defaulting to a blank string. 
WARN[0000] The "PGDATABASE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "PGUSER" variable is not set. Defaulting to a blank string. 
WARN[0000] The "QGISSERVER_URL" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GEOMAPFISH_MAIN_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "QGIS_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GEOMAPFISH_MAIN_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DOCKER_PORT" variable is not set. Defaulting to a blank string. 
WARN[0000] The "FRONT_INNER_PORT" variable is not set. Defaulting to a blank string. 
WARN[0000] The "FRONT_CONFIG" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GEOMAPFISH_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DOCKER_BASE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DOCKER_TAG" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GEOMAPFISH_MAIN_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "SIMPLE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "PGSCHEMA" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GEOMAPFISH_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DOCKER_BASE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DOCKER_TAG" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GEOMAPFISH_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GEOMAPFISH_MAIN_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GIT_HASH" variable is not set. Defaulting to a blank string. 
WARN[0000] The "PGSCHEMA" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DOCKER_BASE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DOCKER_TAG" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GEOMAPFISH_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "PACKAGE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "PACKAGE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GEOMAPFISH_MAIN_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "FRONT_CONFIG" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DOCKER_PORT" variable is not set. Defaulting to a blank string. 
WARN[0000] The "FRONT_INNER_PORT" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DOCKER_BASE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DOCKER_TAG" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GIT_HASH" variable is not set. Defaulting to a blank string. 
WARN[0000] The "PGSCHEMA" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GEOMAPFISH_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GEOMAPFISH_MAIN_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GEOMAPFISH_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "QGISSERVER_URL" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GEOMAPFISH_MAIN_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "QGIS_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "PACKAGE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "PACKAGE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DOCKER_BASE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DOCKER_TAG" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GEOMAPFISH_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "POSTGRES_TAG" variable is not set. Defaulting to a blank string. 
WARN[0000] The "PGPASSWORD" variable is not set. Defaulting to a blank string. 
WARN[0000] The "PGDATABASE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "PGUSER" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GIT_HASH" variable is not set. Defaulting to a blank string. 
WARN[0000] The "PGSCHEMA" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GEOMAPFISH_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GEOMAPFISH_MAIN_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DOCKER_BASE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DOCKER_TAG" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DOCKER_BASE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DOCKER_TAG" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GEOMAPFISH_MAIN_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "SIMPLE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "PGSCHEMA" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GEOMAPFISH_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GEOMAPFISH_MAIN_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DOCKER_BASE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DOCKER_TAG" variable is not set. Defaulting to a blank string. 
WARN[0000] The "SIMPLE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "PGSCHEMA" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GEOMAPFISH_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GEOMAPFISH_MAIN_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GEOMAPFISH_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "PACKAGE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "PACKAGE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DOCKER_BASE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DOCKER_TAG" variable is not set. Defaulting to a blank string. 
WARN[0000] The "POSTGRES_TAG" variable is not set. Defaulting to a blank string. 
WARN[0000] The "PGPASSWORD" variable is not set. Defaulting to a blank string. 
WARN[0000] The "PGDATABASE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "PGUSER" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DOCKER_BASE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DOCKER_TAG" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GEOMAPFISH_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GEOMAPFISH_MAIN_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GIT_HASH" variable is not set. Defaulting to a blank string. 
WARN[0000] The "PGSCHEMA" variable is not set. Defaulting to a blank string. 
WARN[0000] The "FRONT_CONFIG" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DOCKER_PORT" variable is not set. Defaulting to a blank string. 
WARN[0000] The "FRONT_INNER_PORT" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GEOMAPFISH_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GEOMAPFISH_MAIN_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "QGISSERVER_URL" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GEOMAPFISH_MAIN_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "QGIS_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GEOMAPFISH_MAIN_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DOCKER_BASE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DOCKER_TAG" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GEOMAPFISH_MAIN_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GIT_HASH" variable is not set. Defaulting to a blank string. 
WARN[0000] The "PGSCHEMA" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GEOMAPFISH_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DOCKER_BASE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DOCKER_TAG" variable is not set. Defaulting to a blank string. 
WARN[0000] The "SIMPLE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "PGSCHEMA" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GEOMAPFISH_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GEOMAPFISH_MAIN_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DOCKER_BASE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DOCKER_TAG" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GEOMAPFISH_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "PACKAGE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "PACKAGE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GEOMAPFISH_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GEOMAPFISH_MAIN_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GIT_HASH" variable is not set. Defaulting to a blank string. 
WARN[0000] The "PGSCHEMA" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GEOMAPFISH_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GEOMAPFISH_MAIN_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DOCKER_BASE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DOCKER_TAG" variable is not set. Defaulting to a blank string. 
WARN[0000] The "QGISSERVER_URL" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GEOMAPFISH_MAIN_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "QGIS_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "POSTGRES_TAG" variable is not set. Defaulting to a blank string. 
WARN[0000] The "PGPASSWORD" variable is not set. Defaulting to a blank string. 
WARN[0000] The "PGDATABASE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "PGUSER" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GEOMAPFISH_MAIN_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "FRONT_CONFIG" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DOCKER_PORT" variable is not set. Defaulting to a blank string. 
WARN[0000] The "FRONT_INNER_PORT" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DOCKER_BASE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DOCKER_TAG" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GIT_HASH" variable is not set. Defaulting to a blank string. 
WARN[0000] The "PGSCHEMA" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GEOMAPFISH_VERSION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "GEOMAPFISH_MAIN_VERSION" variable is not set. Defaulting to a blank string. 
1 error(s) decoding:

* error decoding 'Ports': No port specified: :<empty>
```

I am installing on Manjaro-Linux with all default parameters and with the default database part. No Proxy.

I'm not familiar with 2.7 yet... Any Idea ?

**Comment by maltaesousa** [comment]
Hi @remyguillaume,
 `pyyaml` was missing in the checks and in the requirements on the readme, I've added it, can you retry, please?

**Comment by remyguillaume** [comment]
Hi @maltaesousa 

It's better, I could build and start a new version, and everything seems to work :)

However, in the Logs I saw an eror message : 

```
Committing first version...
astuce: Utilisation de 'master' comme nom de la branche initiale. Le nom de la branche
astuce: par défaut peut changer. Pour configurer le nom de la branche initiale
astuce: pour tous les nouveaux dépôts, et supprimer cet avertissement, lancez :
astuce: 
astuce: 	git config --global init.defaultBranch <nom>
astuce: 
astuce: Les noms les plus utilisés à la place de 'master' sont 'main', 'trunk' et
astuce: 'development'. La branche nouvellement créée peut être rénommée avec :
astuce: 
astuce: 	git branch -m <nom>
OK.
Compiling GeoMapFish project...
[+] Running 10/11
 ⠿ tilecloudchain Pulled        1.5ss
 ⠿ tools Pulled                 1.5ss
 ⠿ geoportal Pulled             1.6ss
 ⠿ tilegeneration_slave Pulled  1.5ss
 ⠿ alembic Pulled               1.6ss
 ⠿ mapserver Pulled             1.5ss
 ⠿ front Pulled                 1.6ss
 ⠿ print Pulled                 1.6ss
 ⠿ config Error                 1.9ss
 ⠿ tinyows Pulled               1.6ss
 ⠿ redis Pulled                 1.5ss
WARNING: Some service image(s) must be built from source by running:
    docker compose build config
Error response from daemon: pull access denied for camptocamp/my_super_gmf_app-config, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Traceback (most recent call last):
  File "/tmp/gmf/my-super-gmf-app/./build", line 158, in <module>
    main()
  File "/tmp/gmf/my-super-gmf-app/./build", line 127, in main
    run(args, ["docker-compose", "pull"], check=True)  # nosec
  File "/tmp/gmf/my-super-gmf-app/./build", line 22, in run
    subprocess.run(command, **kwargs)  # nosec
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker-compose', 'pull']' returned non-zero exit status 18.
```

I seems it tries to pull the container it is currently bulding (camptocamp/my_super_gmf_app-config).
The application still works at the end, but this error message is not very nice.
Could you look at it before we merge ?
Thanks ! :)

**Comment by maltaesousa** [comment]
@remyguillaume
You're getting this error because you're using docker-compose V2. The error is a known bug: https://github.com/docker/compose/issues/8805

I don't really know what to do... Should we hide this error? Should we prompt a message to tell this error is "normal"?

**Comment by remyguillaume** [comment]
@maltaesousa 
Actually I can reproduce this with docker-compose 1.21.0:

image


I investigate the error, and it comes from the build script : 
https://github.com/camptocamp/c2cgeoportal/blob/d171ebb2ed0ffc8ed5d4f798175f3cc99b6de571/geoportal/c2cgeoportal_geoportal/scaffolds/create/%7B%7Bcookiecutter.project%7D%7D/build#L127

When we execute ./build, the script makes a `docker-compose pull`. This tries to pull ALL images defined in `docker-compose.yaml` services, including the `config` image for example. This can be easily reproduced :

image

Perhaps we should open a ticket @C2C for this?

Otherwise except this error everything works as expected. I think we can merge it as it is, and wait for the bugfix of the build script. What do you think?

**Comment by maltaesousa** [comment]
I cannot reproduce it on v1 ... Also, we have v2.7 in production with compose v1 and this never popped out.
It looks like adding `    pull_policy: never` to the `config` service fixes it so I've added a `sed` to put it in `docker-compose.yaml`

Can you try again, please?

**Comment by remyguillaume** [comment]
Hi @maltaesousa,

Sorry, but we still have debian 10 (buster stable). 
With debian 10 comes docker-compose 1.21.
And docker-compose 1.21 does not support this `pull-policy` parameter yet:

image

I'll see if I can upgrade, but I could take some time...
Otherwise I'll try from home on a newer linux today evening.

Furthermore, I didn't see any required version in the c2cgeoportal docs.
Is this defined anywhere ?

**Comment by maltaesousa** [comment]
Sorry about that, I should've tested v1 after that edit.

I've added a check: if it's compose v2 -> it adds `pull-policy` to the docker-file. If it's v1, it does nothing to the compose file.

`1.21` is 4 years old, I tested with `1.29.2` and it's working great. On my WSL, both compose v1 and v2 are now working. Thanks for the tests you're making at home

**Comment by remyguillaume** [comment]
Hi @maltaesousa, 

```
[XPS-13 gmf]# docker-compose -v
Docker Compose version 2.9.0
```

=> sorry, there is no "v2" in the result string :-)

But I changed the test with the following one, and it worked like a charm:
 
`if docker-compose -v | grep -Ei "v2|version 2" > /dev/null`

For the error with 1.21, I think we do not have to do anything... 4 years old, we just have to update our installation :)

I think you can merge.
Many Thanks for the compatibility with 2.7 :+1:

**Comment by naleiht** [comment]
Thanks for the work ! I tried it on a fresh install and it is failing due to `docker-compose` check. `docker-compose` is now deprecated and has been replaced by `docker compose`. A quirky workaround is to alias `docker-compose` with `docker compose`. 

Got another error (gmf version 2.7)
``` => ERROR [builder 4/4] RUN     cd /tmp/config/geoportal/ &&     c2c-template --vars vars.yaml         --get-config my_super_gmf_app_geoportal/config.yaml         sqlalchemy.url sqlalchemy.pool_recycle sqlalchemy.pool_size sqlalchemy.max_overflow     sqlalchemy.executemany_mode sqlalche  0.7s
------                                                                                                                                                                                                                                                                                                
 > [builder 4/4] RUN     cd /tmp/config/geoportal/ &&     c2c-template --vars vars.yaml         --get-config my_super_gmf_app_geoportal/config.yaml         sqlalchemy.url sqlalchemy.pool_recycle sqlalchemy.pool_size sqlalchemy.max_overflow     sqlalchemy.executemany_mode sqlalchemy_slave.url sqlalchemy_slave.pool_recycle sqlalchemy_slave.pool_size     sqlalchemy_slave.max_overflow sqlalchemy_slave.executemany_mode schema schema_static enable_admin_interface     default_locale_name servers layers cache admin_interface getitfixed functionalities     raster shortener hide_capabilities tinyowsproxy resourceproxy print_url print_get_redirect     checker check_collector default_max_age package srid     reset_password fulltextsearch global_headers headers authorized_referers hooks stats db_chooser     dbsessions urllogin host_forward_host headers_whitelist headers_blacklist     smtp c2c.base_path welcome_email     lingua_extractor interfaces_config interfaces devserver_url api authentication intranet metrics pdfreport     vector_tiles i18next &&     pykwalify --data-file my_super_gmf_app_geoportal/config.yaml         --schema-file CONST_config-schema.yaml &&     rm CONST_* vars.yaml &&     qgisserver-plugin-config my_super_gmf_app_geoportal/config.yaml ../qgisserver/geomapfish.yaml.tmpl:                                                                                                                                                                         
#0 0.399 + cd /tmp/config/geoportal/
#0 0.399 + c2c-template --vars vars.yaml --get-config my_super_gmf_app_geoportal/config.yaml sqlalchemy.url sqlalchemy.pool_recycle sqlalchemy.pool_size sqlalchemy.max_overflow sqlalchemy.executemany_mode sqlalchemy_slave.url sqlalchemy_slave.pool_recycle sqlalchemy_slave.pool_size sqlalchemy_slave.max_overflow sqlalchemy_slave.executemany_mode schema schema_static enable_admin_interface default_locale_name servers layers cache admin_interface getitfixed functionalities raster shortener hide_capabilities tinyowsproxy resourceproxy print_url print_get_redirect checker check_collector default_max_age package srid reset_password fulltextsearch global_headers headers authorized_referers hooks stats db_chooser dbsessions urllogin host_forward_host headers_whitelist headers_blacklist smtp c2c.base_path welcome_email lingua_extractor interfaces_config interfaces devserver_url api authentication intranet metrics pdfreport vector_tiles i18next
#0 0.478 Traceback (most recent call last):
#0 0.478   File "/usr/local/bin/c2c-template", line 8, in <module>
#0 0.478     sys.exit(main())
#0 0.478   File "/usr/local/lib/python3.8/dist-packages/c2c/template/__init__.py", line 159, in main
#0 0.478     do(options)
#0 0.478   File "/usr/local/lib/python3.8/dist-packages/c2c/template/__init__.py", line 290, in do
#0 0.478     used_vars, config = read_vars(options.vars)
#0 0.478   File "/usr/local/lib/python3.8/dist-packages/c2c/template/__init__.py", line 430, in read_vars
#0 0.478     current_vars, config = read_vars(used["extends"])
#0 0.478   File "/usr/local/lib/python3.8/dist-packages/c2c/template/__init__.py", line 420, in read_vars
#0 0.478     with open(vars_file, "r") as file_open:
#0 0.478 FileNotFoundError: [Errno 2] No such file or directory: 'CONST_vars.yaml'
------
failed to solve: executor failed running [/bin/bash -o pipefail -cux cd /tmp/config/geoportal/ &&     c2c-template --vars ${VARS_FILE}         --get-config my_super_gmf_app_geoportal/config.yaml         ${CONFIG_VARS} &&     pykwalify --data-file my_super_gmf_app_geoportal/config.yaml         --schema-file CONST_config-schema.yaml &&     rm CONST_* vars.yaml &&     qgisserver-plugin-config my_super_gmf_app_geoportal/config.yaml ../qgisserver/geomapfish.yaml.tmpl]: exit code: 1```

**Comment by maltaesousa** [comment]
@remyguillaume thanks for the fix

@naleiht can you upload the full `install.log` because it looks like something went wrong in an earlier step

**Comment by remyguillaume** [comment]
@naleiht 

> `docker-compose` is now deprecated and has been replaced by `docker compose`. 

Thanks for your message.
You're right, but it was not planned for the version 2.7 to make this change, and therefore this version is still relying on the old stable `docker-compose`. 

This change will probably be integrated in the next version 2.8 coming next year. 👍

**Comment by naleiht** [comment]
I tried again from a fresh ubuntu 22.04 LTS, installed the official `docker-compose`.

@maltaesousa please find the log
[install.log](https://github.com/geomapfish/getting_started/files/9503500/install.log)
And also the console log, it might provide more information 
[console.log](https://github.com/geomapfish/getting_started/files/9503555/console.log)

Let me know if there is something obvious, otherwise I'll keep investigating today.

**Comment by maltaesousa** [comment]
@naleiht you're not using my branch that is in this PR, you're still in `master`. I can tell because in your `console.log` there's still `[2.6]` as suggested version and and I changed that to `2.7`.

The error you're getting is fixed in this PR, can you checkout to my branch https://github.com/maltaesousa/gmf_getting_started/tree/gmf27 and retry?

Btw, thanks a lot for the tests, the more we have different environments the better it is :)

**Comment by naleiht** [comment]
indeed, that was a rookie mistake. Everything seems fine so far, no installation error, all containers are up and running. Ready to investigate release 2.7 !
Amazing job, thanks for your support.

**Comment by remyguillaume** [comment]
Yeah ! 🤘🏻
Merci 🙂

**Pull request merged**
